# metainfo:
#     gender: 'male'
#     data_dir : parkinglot/
#     subject: "parkinglot"
#     start_frame: 0
#     end_frame: 42

# metainfo:
#     gender: 'male'
#     data_dir : smpl_noscan/
#     subject: "smpl_noscan"
#     start_frame: 0
#     end_frame: 20

# metainfo:
#     gender: 'male'
#     data_dir : smpl_scan/
#     subject: "smpl_scan"
#     start_frame: 0
#     end_frame: 16

metainfo:
    gender: 'male'
    data_dir : smpl_scan_continuous/
    subject: "smpl_scan_continuous"
    start_frame: 0
    end_frame: 40


train:
    type: "Video"
    batch_size: 1
    drop_last: False
    shuffle: True
    worker: 8

    num_sample : 512 

valid:
    type: "VideoVal"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    num_sample : -1
    pixel_per_batch: 1024 

test:
    type: "VideoTest"
    image_id: 0
    batch_size: 1
    drop_last: False
    shuffle: False
    worker: 8

    num_sample : -1
    pixel_per_batch: 1024